### PR TITLE
joyent/kang#7 Update Restify dependencies; drop restify-clients

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by cburroughs** [comment]
This combines the approaches in #8 and #9.

**Comment by cburroughs** [comment]
@melloc @trentm ^^ (The "assign reviewers" button is all grayed out for some reason)

**Comment by cburroughs** [comment]
```
 make test
tools/catest test/tst.env.js test/tst.lib.js test/tst.snapshot_merge.js
Configuration:
    SRC:                         /home/jcsb/src/j/18.4/manta/kang
    Output directory:            /var/tmp/catest.6263
    Temp directory:              /var/tmp/catest.6263_tmpfiles
    Keep successful test output: false
    Found 3 test(s) to run

===================================================

Executing test test/tst.snapshot_merge.js ... success.
Executing test test/tst.lib.js ... success.
Executing test test/tst.env.js ... success.

===================================================

Results:
	Tests passed:	 3/ 3
	Tests failed:	 0/ 3

===================================================
Cleaning up output from successful tests ... done.
```

**Comment by melloc** [comment]
@cburroughs Looks good to me!

**Comment by trentm** [comment]
I made a couple tweaks to package.json, added a CHANGES.md entry and published kang@1.3.0
(and tagged v1.3.0).

**Pull request merged**
